# https://taskfile.dev

version: "3"

tasks:
  http:
    cmd: go run ./cmd/http
    silent: true
  gen:
    silent: true
    deps:
      - gen:converter
      - gen:goa
  gen:converter:
    cmd: goverter gen -cwd . ./app/...
    silent: true
    ignore_error: true
    sources:
      - "app/**/converter.go"
  gen:goa:
    cmd: goa gen flow-editor-server/design
    silent: true
    ignore_error: true
    sources:
      - "design/**.go"
  docs:
    cmd: redocly preview-docs ./gen/http/openapi3.yaml -p 3001
    silent: true
  opa:
    cmd: opa run -w -a localhost:8181 -s -b policy
    silent: true
