# https://taskfile.dev

version: "3"

tasks:
  http:
    cmds:
      - go run ./cmd/http
    silent: true
  gen:
    silent: true
    deps:
      - gen:converter
      - gen:goa
  gen:converter:
    cmds:
      - goverter gen -cwd . ./app/...
    silent: true
    sources:
      - "app/**/converter.go"
  gen:goa:
    cmds:
      - goa gen flow-editor-server/design
    silent: true
    sources:
      - "design/**.go"
