---
server:
  http_listen_port: 3100

auth_enabled: false

schema_config:
  configs:
    - from: 2023-01-05
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
  filesystem:
    directory: /tmp/loki/chunks
