server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml # This location needs to be writeable by Promtail.

clients:
  - url: http://192.168.31.170:3100/loki/api/v1/push

scrape_configs:
  - job_name: app
    pipeline_stages:
      - json:
          expressions:
            message: message
            time: time
            level: level
      - labels:
          message:
          time:
          level:
    static_configs:
      - targets:
          - localhost
        labels:
          app: flow-editor
          type: service
          __path__: /var/log/app.log # The path matching uses a third party library: https://github.com/bmatcuk/doublestar
      - targets:
          - localhost
        labels:
          app: flow-editor
          type: access
          __path__: /var/log/access.log
