swagger: "2.0"
info:
    title: 流程编辑器 API
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /account:
        get:
            tags:
                - account
            summary: getAccount account
            description: Get account
            operationId: account#getAccount
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AccountGetAccountResponseBody'
            schemes:
                - http
definitions:
    AccountGetAccountResponseBody:
        title: AccountGetAccountResponseBody
        type: object
        properties:
            activated:
                type: boolean
                example: true
            membership:
                type: integer
                example: 1747045543197819866
                format: int64
        example:
            activated: true
            membership: 7309928978923691591
