openapi: 3.0.3
info:
    title: 流程编辑器 API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for flow-editor-server
paths:
    /account:
        get:
            tags:
                - account
            summary: getAccount account
            description: Get account
            operationId: account#getAccount
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AccountInfo'
                            example:
                                activated: true
                                membership: 4248600860158212725
                                roles:
                                    - Est iste sapiente sint veritatis sunt et.
                                    - Consequatur et reiciendis vitae quidem.
                                    - Earum sed similique delectus autem.
                                user_id: Consequatur pariatur architecto possimus rerum eaque ea.
    /flow:
        get:
            tags:
                - flow
            summary: getFlowList flow
            description: 列出当前用户拥有的 flow
            operationId: flow#getFlowList
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/FlowListItemData'
                                example:
                                    - created_at: Expedita ut omnis quam.
                                      id: 5491639435536833503
                                      title: Reprehenderit placeat.
                                    - created_at: Expedita ut omnis quam.
                                      id: 5491639435536833503
                                      title: Reprehenderit placeat.
                                    - created_at: Expedita ut omnis quam.
                                      id: 5491639435536833503
                                      title: Reprehenderit placeat.
                            example:
                                - created_at: Expedita ut omnis quam.
                                  id: 5491639435536833503
                                  title: Reprehenderit placeat.
                                - created_at: Expedita ut omnis quam.
                                  id: 5491639435536833503
                                  title: Reprehenderit placeat.
                                - created_at: Expedita ut omnis quam.
                                  id: 5491639435536833503
                                  title: Reprehenderit placeat.
        post:
            tags:
                - flow
            summary: createFlow flow
            description: 创建 flow
            operationId: flow#createFlow
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateFlowRequestBody'
                        example:
                            edges: Error non tempore.
                            nodes: Qui veniam quo nostrum odit quo.
                            title: Dolor cum consequuntur eligendi.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FlowDetailData'
                            example:
                                created_at: Vel consequuntur quia neque.
                                edges: Maxime omnis porro at laborum.
                                id: 4246908477237644263
                                nodes: Ut accusantium.
                                title: Porro voluptas a.
    /flow/{id}:
        delete:
            tags:
                - flow
            summary: deleteFlow flow
            description: 删除 flow
            operationId: flow#deleteFlow
            parameters:
                - name: id
                  in: path
                  description: 要删除的 flow id
                  required: true
                  schema:
                    type: string
                    description: 要删除的 flow id
                    example: Nihil vel reprehenderit laudantium totam.
                  example: Et consequuntur vel.
            responses:
                "204":
                    description: No Content response.
        get:
            tags:
                - flow
            summary: getFlow flow
            description: 根据 flow id 获取 flow 详情
            operationId: flow#getFlow
            parameters:
                - name: id
                  in: path
                  description: 要获取的 flow id
                  required: true
                  schema:
                    type: string
                    description: 要获取的 flow id
                    example: Qui assumenda quibusdam architecto.
                  example: Est assumenda iusto itaque omnis.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FlowDetailData'
                            example:
                                created_at: Illum et consequatur quis voluptatum assumenda.
                                edges: Qui eum asperiores reiciendis corporis aliquam sunt.
                                id: 5894164223073658948
                                nodes: Ipsa quo quasi.
                                title: Ipsum est ab est illo sequi molestias.
        put:
            tags:
                - flow
            summary: updateFlow flow
            description: 更新 flow
            operationId: flow#updateFlow
            parameters:
                - name: id
                  in: path
                  description: 要更新的 flow id
                  required: true
                  schema:
                    type: string
                    description: 要更新的 flow id
                    example: Expedita dolorem ut magnam consequatur doloribus.
                  example: Et doloremque fugit occaecati dolores suscipit perferendis.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateFlowRequestBody'
                        example:
                            edges: Nisi sint voluptates cupiditate dignissimos qui sit.
                            nodes: Ut minus dolores consequatur eius esse.
                            title: Minus reprehenderit laboriosam deserunt sit voluptates.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FlowDetailData'
                            example:
                                created_at: Accusamus saepe nemo.
                                edges: Sint asperiores nobis vitae eos.
                                id: 1167611504762411030
                                nodes: Ut odit vero rerum qui sint.
                                title: Doloribus rerum rerum voluptas et eos aut.
    /flow/{id}/copy:
        post:
            tags:
                - flow
            summary: copyFlow flow
            description: 复制 flow
            operationId: flow#copyFlow
            parameters:
                - name: id
                  in: path
                  description: 要复制的 flow id
                  required: true
                  schema:
                    type: string
                    description: 要复制的 flow id
                    example: Optio voluptatem doloribus.
                  example: Animi est in impedit esse libero autem.
            responses:
                "201":
                    description: Created response.
components:
    schemas:
        AccountInfo:
            type: object
            properties:
                activated:
                    type: boolean
                    example: false
                membership:
                    type: integer
                    example: 388031239930522295
                    format: int64
                roles:
                    type: array
                    items:
                        type: string
                        example: Est omnis architecto excepturi sit.
                    example:
                        - Omnis quia quo architecto sed aperiam ullam.
                        - Nam ut est sequi.
                        - Atque minus vel vero doloribus vel.
                user_id:
                    type: string
                    example: Consequuntur et.
            example:
                activated: true
                membership: 6167860447850313283
                roles:
                    - Cupiditate et aut vero quia facilis saepe.
                    - Aliquam dolorum et accusantium.
                user_id: Occaecati veniam quam architecto earum soluta pariatur.
            required:
                - user_id
                - activated
                - membership
                - roles
        CreateFlowRequestBody:
            type: object
            properties:
                edges:
                    type: string
                    description: flow 边
                    example: Ex et aut sed enim.
                nodes:
                    type: string
                    description: flow 节点
                    example: Temporibus voluptas.
                title:
                    type: string
                    description: flow 标题
                    example: Dolor sunt sint.
            example:
                edges: Ullam enim.
                nodes: Tenetur itaque similique et vitae reiciendis.
                title: Maiores fugiat.
        FlowDetailData:
            type: object
            properties:
                created_at:
                    type: string
                    description: flow 创建时间
                    example: Eligendi voluptas sequi saepe quia.
                edges:
                    type: string
                    description: flow 边
                    example: Repellendus voluptas.
                id:
                    type: integer
                    description: flow id
                    example: 7474924033919102999
                    format: int64
                nodes:
                    type: string
                    description: flow 节点
                    example: Est earum nesciunt et.
                title:
                    type: string
                    description: flow 标题
                    example: Earum voluptatem nemo dolorem suscipit eos est.
            example:
                created_at: Molestiae est asperiores et quis.
                edges: Laborum architecto inventore dicta exercitationem.
                id: 4162289681499716662
                nodes: Eum dolorem inventore aut officiis.
                title: Aperiam molestiae quo perferendis.
            required:
                - id
                - title
                - created_at
        FlowListItemData:
            type: object
            properties:
                created_at:
                    type: string
                    description: flow 创建时间
                    example: Dolores ex rerum consequatur.
                id:
                    type: integer
                    description: flow id
                    example: 7454326162427327981
                    format: int64
                title:
                    type: string
                    description: flow 标题
                    example: Ratione consequuntur.
            example:
                created_at: Magni deleniti sint saepe deleniti.
                id: 338101955933799849
                title: Accusantium et necessitatibus ut cumque reiciendis et.
            required:
                - id
                - title
                - created_at
tags:
    - name: account
      description: Account service
    - name: flow
      description: Flow 服务
