swagger: "2.0"
info:
    title: 流程编辑器 API
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /account:
        get:
            tags:
                - account
            summary: getAccount account
            description: Get account
            operationId: account#getAccount
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AccountGetAccountResponseBody'
                        required:
                            - activated
                            - membership
            schemes:
                - http
    /flow:
        get:
            tags:
                - flow
            summary: getFlowList flow
            description: 列出当前用户拥有的 flow
            operationId: flow#getFlowList
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/FlowListItemResponse'
            schemes:
                - http
        post:
            tags:
                - flow
            summary: createFlow flow
            description: 创建 flow
            operationId: flow#createFlow
            parameters:
                - name: CreateFlowRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/FlowCreateFlowRequestBody'
                    required:
                        - title
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/FlowCreateFlowResponseBody'
                        required:
                            - id
                            - title
                            - created_at
            schemes:
                - http
    /flow/{id}:
        get:
            tags:
                - flow
            summary: getFlow flow
            description: 根据 flow id 获取 flow 详情
            operationId: flow#getFlow
            parameters:
                - name: id
                  in: path
                  description: 要获取的 flow id
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/FlowGetFlowResponseBody'
                        required:
                            - id
                            - title
                            - created_at
            schemes:
                - http
        put:
            tags:
                - flow
            summary: updateFlow flow
            description: 更新 flow
            operationId: flow#updateFlow
            parameters:
                - name: id
                  in: path
                  description: 要更新的 flow id
                  required: true
                  type: string
                - name: UpdateFlowRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/FlowUpdateFlowRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/FlowUpdateFlowResponseBody'
                        required:
                            - id
                            - title
                            - created_at
            schemes:
                - http
        delete:
            tags:
                - flow
            summary: deleteFlow flow
            description: 删除 flow
            operationId: flow#deleteFlow
            parameters:
                - name: id
                  in: path
                  description: 要删除的 flow id
                  required: true
                  type: string
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
    /flow/{id}/copy:
        post:
            tags:
                - flow
            summary: copyFlow flow
            description: 复制 flow
            operationId: flow#copyFlow
            parameters:
                - name: id
                  in: path
                  description: 要复制的 flow id
                  required: true
                  type: string
            responses:
                "201":
                    description: Created response.
            schemes:
                - http
definitions:
    AccountGetAccountResponseBody:
        title: AccountGetAccountResponseBody
        type: object
        properties:
            activated:
                type: boolean
                example: true
            membership:
                type: integer
                example: 2403486949651356170
                format: int64
        example:
            activated: false
            membership: 404467491484711029
        required:
            - activated
            - membership
    FlowCreateFlowRequestBody:
        title: FlowCreateFlowRequestBody
        type: object
        properties:
            edges:
                type: string
                description: flow 边
                example: Qui deleniti et est quas at.
            nodes:
                type: string
                description: flow 节点
                example: Minus doloremque blanditiis consequatur voluptate et.
            title:
                type: string
                description: flow 标题
                example: Sed culpa vitae.
        example:
            edges: Provident veniam porro ducimus voluptatem consequatur asperiores.
            nodes: Autem quibusdam quis delectus.
            title: Quibusdam reprehenderit dolorem nesciunt alias.
        required:
            - title
    FlowCreateFlowResponseBody:
        title: FlowCreateFlowResponseBody
        type: object
        properties:
            created_at:
                type: string
                description: flow 创建时间
                example: Laboriosam laudantium.
            edges:
                type: string
                description: flow 边
                example: Officiis non illum possimus sit tenetur.
            id:
                type: integer
                description: flow id
                example: 7055418067584315525
                format: int64
            nodes:
                type: string
                description: flow 节点
                example: Beatae consequatur velit libero qui deleniti dolorum.
            title:
                type: string
                description: flow 标题
                example: Molestiae aut omnis.
        example:
            created_at: Deserunt blanditiis rerum quae itaque.
            edges: Voluptas quod possimus earum repudiandae iusto nobis.
            id: 5905438953811239422
            nodes: Ut repellendus molestiae consequuntur amet.
            title: Quae impedit quo.
        required:
            - id
            - title
            - created_at
    FlowGetFlowResponseBody:
        title: FlowGetFlowResponseBody
        type: object
        properties:
            created_at:
                type: string
                description: flow 创建时间
                example: Ratione ab excepturi aut doloribus alias.
            edges:
                type: string
                description: flow 边
                example: Maiores corporis.
            id:
                type: integer
                description: flow id
                example: 8621733761409741819
                format: int64
            nodes:
                type: string
                description: flow 节点
                example: Debitis qui praesentium.
            title:
                type: string
                description: flow 标题
                example: Asperiores nobis vitae eos vel accusamus saepe.
        example:
            created_at: Autem sapiente et.
            edges: Commodi consequatur et.
            id: 2500838439770270367
            nodes: Vitae asperiores omnis.
            title: Repudiandae minima similique ducimus optio velit voluptate.
        required:
            - id
            - title
            - created_at
    FlowListItemResponse:
        title: FlowListItemResponse
        type: object
        properties:
            created_at:
                type: string
                description: flow 创建时间
                example: Similique est tempore.
            id:
                type: integer
                description: flow id
                example: 6419423105656687679
                format: int64
            title:
                type: string
                description: flow 标题
                example: Dignissimos qui sit.
        example:
            created_at: Ut odit vero rerum qui sint.
            id: 1167611504762411030
            title: Doloribus rerum rerum voluptas et eos aut.
        required:
            - id
            - title
            - created_at
    FlowUpdateFlowRequestBody:
        title: FlowUpdateFlowRequestBody
        type: object
        properties:
            edges:
                type: string
                description: flow 边
                example: Beatae quia nihil eius unde consequatur.
            nodes:
                type: string
                description: flow 节点
                example: Voluptas iure assumenda quos quae.
            title:
                type: string
                description: flow 标题
                example: Ut quis et repellat facere et.
        example:
            edges: Aut aperiam repellendus fugit facilis.
            nodes: Atque dolor tempore alias ut.
            title: Nesciunt ad dolores aut incidunt sit architecto.
    FlowUpdateFlowResponseBody:
        title: FlowUpdateFlowResponseBody
        type: object
        properties:
            created_at:
                type: string
                description: flow 创建时间
                example: Magnam repudiandae error numquam.
            edges:
                type: string
                description: flow 边
                example: Iste ab.
            id:
                type: integer
                description: flow id
                example: 7124095684933745533
                format: int64
            nodes:
                type: string
                description: flow 节点
                example: In itaque et.
            title:
                type: string
                description: flow 标题
                example: Corrupti reprehenderit laudantium est optio aperiam at.
        example:
            created_at: Non perferendis possimus sint.
            edges: Ex quae rerum modi.
            id: 6419679406707055543
            nodes: Beatae distinctio dolorem reprehenderit aliquam animi at.
            title: Deserunt omnis veniam.
        required:
            - id
            - title
            - created_at
