openapi: 3.0.3
info:
    title: 流程编辑器 API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for flow-editor-server
paths:
    /account:
        get:
            tags:
                - account
            summary: getAccount account
            description: Get account
            operationId: account#getAccount
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AccountInfo'
                            example:
                                activated: false
                                membership: 1579757196300768946
                                roles:
                                    - Corporis totam.
                                    - Pariatur architecto possimus rerum eaque ea.
                                    - Est quasi.
                                    - Est iste sapiente sint veritatis sunt et.
                                user_id: Fugiat perferendis.
    /flow:
        get:
            tags:
                - flow
            summary: getFlowList flow
            description: 列出当前用户拥有的 flow
            operationId: flow#getFlowList
            parameters:
                - name: name
                  in: query
                  description: 流程名
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: 流程名
                    example: Aliquam dolorum et accusantium.
                  example: Fugiat ratione consequuntur sint.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/FlowListItemData'
                                example:
                                    - created_at: Autem necessitatibus.
                                      id: 532996196428889293
                                      title: Sed similique.
                                    - created_at: Autem necessitatibus.
                                      id: 532996196428889293
                                      title: Sed similique.
                                    - created_at: Autem necessitatibus.
                                      id: 532996196428889293
                                      title: Sed similique.
                                    - created_at: Autem necessitatibus.
                                      id: 532996196428889293
                                      title: Sed similique.
                            example:
                                - created_at: Autem necessitatibus.
                                  id: 532996196428889293
                                  title: Sed similique.
                                - created_at: Autem necessitatibus.
                                  id: 532996196428889293
                                  title: Sed similique.
                                - created_at: Autem necessitatibus.
                                  id: 532996196428889293
                                  title: Sed similique.
                                - created_at: Autem necessitatibus.
                                  id: 532996196428889293
                                  title: Sed similique.
        post:
            tags:
                - flow
            summary: createFlow flow
            description: 创建 flow
            operationId: flow#createFlow
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateFlowRequestBody'
                        example:
                            data: Quasi vitae qui.
                            title: Qui ipsa.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FlowDetailData'
                            example:
                                created_at: Quis dolor cum consequuntur eligendi fugit qui.
                                data: Dolore illum et consequatur quis voluptatum.
                                id: 831723134999124294
                                title: Reiciendis corporis aliquam.
    /flow/{id}:
        delete:
            tags:
                - flow
            summary: deleteFlow flow
            description: 删除 flow
            operationId: flow#deleteFlow
            parameters:
                - name: id
                  in: path
                  description: 要删除的 flow id
                  required: true
                  schema:
                    type: string
                    description: 要删除的 flow id
                    example: Ullam est earum nesciunt et.
                  example: Repellendus voluptas.
            responses:
                "204":
                    description: No Content response.
        get:
            tags:
                - flow
            summary: getFlow flow
            description: 根据 flow id 获取 flow 详情
            operationId: flow#getFlow
            parameters:
                - name: id
                  in: path
                  description: 要获取的 flow id
                  required: true
                  schema:
                    type: string
                    description: 要获取的 flow id
                    example: Rerum consequatur sunt vitae accusantium et.
                  example: Ut cumque reiciendis et veritatis magni deleniti.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FlowDetailData'
                            example:
                                created_at: Est ab est illo sequi.
                                data: Iure quia quam at repudiandae.
                                id: 7586672659878409806
                                title: Impedit beatae nihil voluptas laudantium fugit.
        put:
            tags:
                - flow
            summary: updateFlow flow
            description: 更新 flow
            operationId: flow#updateFlow
            parameters:
                - name: id
                  in: path
                  description: 要更新的 flow id
                  required: true
                  schema:
                    type: string
                    description: 要更新的 flow id
                    example: Saepe deleniti qui deserunt eum earum voluptatem.
                  example: Dolorem suscipit eos.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateFlowData'
                        example:
                            data: Et ut porro voluptas a et ut.
                            title: Amet error non.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FlowDetailData'
                            example:
                                created_at: Asperiores iste voluptas.
                                data: Non consequatur dicta.
                                id: 3943196594614256413
                                title: At laborum molestiae vel consequuntur quia.
    /flow/{id}/copy:
        post:
            tags:
                - flow
            summary: copyFlow flow
            description: 复制 flow
            operationId: flow#copyFlow
            parameters:
                - name: id
                  in: path
                  description: 要复制的 flow id
                  required: true
                  schema:
                    type: string
                    description: 要复制的 flow id
                    example: Eligendi voluptas sequi saepe quia.
                  example: Omnis aperiam molestiae quo perferendis.
            responses:
                "201":
                    description: Created response.
components:
    schemas:
        AccountInfo:
            type: object
            properties:
                activated:
                    type: boolean
                    example: true
                membership:
                    type: integer
                    example: 6077889507282666396
                    format: int64
                roles:
                    type: array
                    items:
                        type: string
                        example: Ut illo.
                    example:
                        - Fuga voluptas voluptas.
                        - Et exercitationem.
                        - Ipsum deserunt architecto.
                user_id:
                    type: string
                    example: Aut aperiam repellendus fugit facilis.
            example:
                activated: true
                membership: 4584344530721600254
                roles:
                    - Optio consectetur quo possimus nobis dignissimos sint.
                    - Molestias et fuga beatae.
                user_id: Eligendi nostrum.
            required:
                - user_id
                - activated
                - membership
                - roles
        CreateFlowRequestBody:
            type: object
            properties:
                data:
                    type: string
                    description: flow 数据
                    example: Officia aut est omnis.
                title:
                    type: string
                    description: flow 标题
                    example: Consequuntur et.
            example:
                data: Quo architecto sed aperiam ullam debitis nam.
                title: Excepturi sit alias minus omnis.
            required:
                - title
        FlowDetailData:
            type: object
            properties:
                created_at:
                    type: string
                    description: flow 创建时间
                    example: Quas et voluptatum iure voluptas aperiam.
                data:
                    type: string
                    description: flow 数据
                    example: Porro nam ut.
                id:
                    type: integer
                    description: flow id
                    example: 8899814133664666986
                    format: int64
                title:
                    type: string
                    description: flow 标题
                    example: Id voluptatem quis nihil.
            example:
                created_at: Adipisci explicabo eveniet cum unde quam.
                data: Vel in et fugiat.
                id: 3851920108255156483
                title: Maxime ipsam veritatis vel voluptate rerum.
            required:
                - id
                - title
                - created_at
        FlowListItemData:
            type: object
            properties:
                created_at:
                    type: string
                    description: flow 创建时间
                    example: Ipsa consequatur et neque.
                id:
                    type: integer
                    description: flow id
                    example: 1445275778560579091
                    format: int64
                title:
                    type: string
                    description: flow 标题
                    example: Autem esse illo qui repudiandae ipsum aut.
            example:
                created_at: Magnam maxime repudiandae consequatur ratione.
                id: 2062647879852682326
                title: Eaque rerum reprehenderit autem.
            required:
                - id
                - title
                - created_at
        UpdateFlowData:
            type: object
            properties:
                data:
                    type: string
                    description: flow 数据
                    example: Doloribus vel quidem occaecati veniam.
                title:
                    type: string
                    description: flow 标题
                    example: Est sequi sit atque minus vel.
            example:
                data: Cupiditate et aut vero quia facilis saepe.
                title: Architecto earum soluta pariatur voluptatem voluptatem beatae.
tags:
    - name: account
      description: Account service
    - name: flow
      description: Flow 服务
