openapi: 3.0.3
info:
    title: 流程编辑器 API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for flow-editor-server
paths:
    /account:
        get:
            tags:
                - account
            summary: getAccount account
            description: Get account
            operationId: account#getAccount
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AccountInfo'
                            example:
                                activated: true
                                membership: 4298488840961716468
    /flow:
        get:
            tags:
                - flow
            summary: getFlowList flow
            description: 列出当前用户拥有的 flow
            operationId: flow#getFlowList
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/FlowListItem'
                                example:
                                    - created_at: Natus ad sunt.
                                      id: 7235766206988876182
                                      title: In exercitationem qui.
                                    - created_at: Natus ad sunt.
                                      id: 7235766206988876182
                                      title: In exercitationem qui.
                                    - created_at: Natus ad sunt.
                                      id: 7235766206988876182
                                      title: In exercitationem qui.
                                    - created_at: Natus ad sunt.
                                      id: 7235766206988876182
                                      title: In exercitationem qui.
                            example:
                                - created_at: Natus ad sunt.
                                  id: 7235766206988876182
                                  title: In exercitationem qui.
                                - created_at: Natus ad sunt.
                                  id: 7235766206988876182
                                  title: In exercitationem qui.
        post:
            tags:
                - flow
            summary: createFlow flow
            description: 创建 flow
            operationId: flow#createFlow
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateFlowRequestBody'
                        example:
                            edges: Ut omnis quam.
                            nodes: Veritatis reprehenderit placeat quis.
                            title: Delectus autem.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FlowDetail'
                            example:
                                created_at: Est ab est illo sequi.
                                edges: Iure quia quam at repudiandae.
                                id: 3038076054949331897
                                nodes: Impedit beatae nihil voluptas laudantium fugit.
                                title: Omnis repellendus in.
    /flow/{id}:
        delete:
            tags:
                - flow
            summary: deleteFlow flow
            description: 删除 flow
            operationId: flow#deleteFlow
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Doloribus vel quidem occaecati veniam.
                  example: Architecto earum soluta pariatur voluptatem voluptatem beatae.
            responses:
                "204":
                    description: No Content response.
        get:
            tags:
                - flow
            summary: getFlow flow
            description: 根据 flow id 获取 flow 详情
            operationId: flow#getFlow
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Sit alias minus omnis quia quo.
                  example: Sed aperiam.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FlowDetail'
                            example:
                                created_at: Reiciendis vitae quidem non earum sed.
                                edges: Veritatis sunt et consequatur consequatur.
                                id: 6556399940084643054
                                nodes: Iste sapiente.
                                title: Quasi magni.
        put:
            tags:
                - flow
            summary: updateFlow flow
            description: 更新 flow
            operationId: flow#updateFlow
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: string
                    example: Debitis nam ut est.
                  example: Sit atque minus vel.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateFlowData'
                        example:
                            edges: Dolore illum et consequatur quis voluptatum.
                            nodes: Asperiores reiciendis corporis aliquam.
                            title: Quasi vitae qui.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FlowDetail'
                            example:
                                created_at: Porro at laborum molestiae vel consequuntur quia.
                                edges: Quo maxime.
                                id: 2652477686754843736
                                nodes: Et ut porro voluptas a et ut.
                                title: Nostrum odit quo amet error non.
components:
    schemas:
        AccountInfo:
            type: object
            properties:
                activated:
                    type: boolean
                    example: true
                membership:
                    type: integer
                    example: 8145389665010042811
                    format: int64
            example:
                activated: true
                membership: 8310704061277884680
            required:
                - activated
                - membership
        CreateFlowRequestBody:
            type: object
            properties:
                edges:
                    type: string
                    description: flow 边
                    example: Adipisci ex.
                nodes:
                    type: string
                    description: flow 节点
                    example: Autem fugiat magnam maxime repudiandae consequatur.
                title:
                    type: string
                    description: flow 标题
                    example: Debitis eaque rerum.
            example:
                edges: Quas et voluptatum iure voluptas aperiam.
                nodes: Porro nam ut.
                title: Id voluptatem quis nihil.
            required:
                - title
        FlowDetail:
            type: object
            properties:
                created_at:
                    type: string
                    description: flow 创建时间
                    example: Voluptas optio consectetur quo possimus nobis.
                edges:
                    type: string
                    description: flow 边
                    example: Reiciendis eligendi nostrum odit voluptatem.
                id:
                    type: integer
                    description: flow id
                    example: 5604669765176843498
                    format: int64
                nodes:
                    type: string
                    description: flow 节点
                    example: Voluptas minima et exercitationem omnis ipsum deserunt.
                title:
                    type: string
                    description: flow 标题
                    example: Cumque odio fuga.
            example:
                created_at: Consequatur et neque.
                edges: Illo qui repudiandae ipsum aut distinctio.
                id: 7895679563155964847
                nodes: Fuga beatae et suscipit autem.
                title: In molestias.
            required:
                - id
                - title
                - created_at
        FlowListItem:
            type: object
            properties:
                created_at:
                    type: string
                    description: flow 创建时间
                    example: Sit architecto vero atque dolor.
                id:
                    type: integer
                    description: flow id
                    example: 8722789520435035405
                    format: int64
                title:
                    type: string
                    description: flow 标题
                    example: Consequatur est nesciunt ad dolores aut.
            example:
                created_at: Facilis dolorum ut.
                id: 2617634455243736260
                title: Ut cum aut aperiam repellendus.
            required:
                - id
                - title
                - created_at
        UpdateFlowData:
            type: object
            properties:
                edges:
                    type: string
                    description: flow 边
                    example: In et fugiat.
                nodes:
                    type: string
                    description: flow 节点
                    example: Veritatis vel voluptate rerum minus.
                title:
                    type: string
                    description: flow 标题
                    example: Libero maxime.
            example:
                edges: Officia aut est omnis.
                nodes: Consequuntur et.
                title: Adipisci explicabo eveniet cum unde quam.
tags:
    - name: account
      description: Account service
    - name: flow
      description: Flow 服务
