# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: flow
generate:
  echo-server: true
  models: true
output: ../../app/flow/api_gen.go
