services:
  cerbos:
    image: ghcr.io/cerbos/cerbos:0.36.0
    ports:
      - "3592:3592"
      - "3593:3593"
    volumes:
      - "../policy/cerbos:/policies"
      - "./config/cerbos.yaml:/config/cerbos.yaml"
    command: [server, --config=config/cerbos.yaml]

  promtail:
    image: grafana/promtail
    ports:
      - "9080:9080"
    volumes:
      - "./config/promtail.yaml:/mnt/config/promtail.yaml"
      - "../logs:/var/log"
    command: [--config.file=/mnt/config/promtail.yaml]
