// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package account

import account "flow-editor-server/gen/account"

type ConverterImpl struct{}

func (c *ConverterImpl) FromAccountModelToAccountInfo(source AccountModel) *account.AccountInfo {
	var accountAccountInfo account.AccountInfo
	accountAccountInfo.Activated = source.Activated
	accountAccountInfo.Membership = int(source.Membership)
	return &accountAccountInfo
}
