// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package account

import account "flow-editor-server/gen/account"

type ConverterImpl struct{}

func (c *ConverterImpl) AccountToAccountInfo(source Account) *account.AccountInfo {
	var accountAccountInfo account.AccountInfo
	accountAccountInfo.UserID = source.UserID
	accountAccountInfo.Activated = source.Activated
	accountAccountInfo.Membership = int(source.Membership)
	if source.Roles != nil {
		accountAccountInfo.Roles = make([]string, len(source.Roles))
		for i := 0; i < len(source.Roles); i++ {
			accountAccountInfo.Roles[i] = RoleToString(source.Roles[i])
		}
	}
	return &accountAccountInfo
}
