// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package flow

type ConverterImpl struct{}

func (c *ConverterImpl) ConvertFlowDetail(source FlowDetail) GetFlowIdJSONBody {
	var flowGetFlowIdJSONBody GetFlowIdJSONBody
	flowGetFlowIdJSONBody.CreatedAt = TimeToString(source.CreatedAt)
	flowGetFlowIdJSONBody.Edges = source.Edges
	flowGetFlowIdJSONBody.Id = source.Id
	flowGetFlowIdJSONBody.Nodes = source.Nodes
	flowGetFlowIdJSONBody.Title = source.Title
	return flowGetFlowIdJSONBody
}
func (c *ConverterImpl) ConvertPostFlowJSONRequestBody(source PostFlowJSONRequestBody) CreateFlowData {
	var flowCreateFlowData CreateFlowData
	flowCreateFlowData.Title = source.Title
	var pString *string
	if source.Nodes != nil {
		xstring := *source.Nodes
		pString = &xstring
	}
	flowCreateFlowData.Nodes = pString
	var pString2 *string
	if source.Edges != nil {
		xstring2 := *source.Edges
		pString2 = &xstring2
	}
	flowCreateFlowData.Edges = pString2
	return flowCreateFlowData
}
func (c *ConverterImpl) ConvertSliceFlowListItem(source []FlowListItem) []FlowListItemRes {
	var flowFlowListItemResList []FlowListItemRes
	if source != nil {
		flowFlowListItemResList = make([]FlowListItemRes, len(source))
		for i := 0; i < len(source); i++ {
			flowFlowListItemResList[i] = c.flowFlowListItemToFlowFlowListItemRes(source[i])
		}
	}
	return flowFlowListItemResList
}
func (c *ConverterImpl) flowFlowListItemToFlowFlowListItemRes(source FlowListItem) FlowListItemRes {
	var flowFlowListItemRes FlowListItemRes
	flowFlowListItemRes.CreatedAt = TimeToString(source.CreatedAt)
	flowFlowListItemRes.Id = source.Id
	flowFlowListItemRes.Title = source.Title
	return flowFlowListItemRes
}
