apiVersion: 1

datasources:
  - name: Loki
    uid: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          matcherType: label
          matcherRegex: trace_id
          url: '$${__value.raw}'
          datasourceUid: Tempo
  - name: Tempo
    uid: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      tracesToLogsV2:
        tags:
          - key: service.name
            value: app
        datasourceUid: Loki
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        customQuery: true
        query: '{$${__tags}, trace_id="$${__trace.traceId}"}'
