definitions:
  account.AccountOutput:
    properties:
      activated:
        type: boolean
      membership:
        type: integer
    type: object
  flow.CreateFlowInput:
    properties:
      edges:
        type: string
      nodes:
        type: string
      owner:
        type: string
      title:
        type: string
    type: object
  flow.FlowDetailOutput:
    properties:
      createdAt:
        type: string
      edges:
        type: string
      id:
        type: integer
      nodes:
        type: string
      title:
        type: string
    type: object
  flow.FlowListObjectOutput:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
  flow.UpdateFlowInput:
    properties:
      edges:
        type: string
      id:
        type: integer
      nodes:
        type: string
      owner:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
  description: Flow Editor APIs
  title: Flow Editor
  version: "1.0"
paths:
  /account:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.AccountOutput'
      summary: get account
      tags:
      - account
  /flow:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/flow.FlowListObjectOutput'
            type: array
      summary: get flow list
      tags:
      - flow
    post:
      consumes:
      - application/json
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/flow.CreateFlowInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/flow.FlowDetailOutput'
      summary: create flow
      tags:
      - flow
  /flow/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: flow id
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
      summary: delete flow
      tags:
      - flow
    get:
      parameters:
      - description: flow id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/flow.FlowDetailOutput'
      summary: get flow detail
      tags:
      - flow
    put:
      consumes:
      - application/json
      parameters:
      - description: flow id
        in: path
        name: id
        required: true
        type: string
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/flow.UpdateFlowInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/flow.FlowDetailOutput'
      summary: update flow
      tags:
      - flow
swagger: "2.0"
